# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tsuN7VFqUiNtOKiQ5FrgBcln5fc5X-5u
"""

import time
import threading

def sq_num(numbers):
  print("sq numbers: ")
  for j in numbers:
    time.sleep(0.2)
    print("square: ", j*j)

def cal_cube(numbers):
  print("Cube numbers: ")
  for j in numbers:
    time.sleep(0.2)
    print("cube: ", j*j*j)

queue=[1,2,3,4,5]
t1=time.time()
t2=threading.Thread(target=sq_num, args=(queue,)) 
t3=threading.Thread(target=cal_cube, args=(queue,))   

t2.start()
t3.start()

t2.join()
t3.join()

print("Time taken= " , time.time()-t1)